#import "/lib.typ": TODO, DONE, SKIP, add-edges, list-todos
#list-todos()
#line(length: 100%)
#TODO([n0], "n0"                ) ;#linebreak()
#TODO([n1], "n1", fmt:"full"    ) ;#linebreak()
#TODO([n2], "n2", fmt:"compact" ) ;#linebreak()
#TODO([n3], "n3", fmt:"none"    ) ;#linebreak()
#DONE([o0], "o0"                ) ;#linebreak()
#DONE([o1], "o1", fmt:"full"    ) ;#linebreak()
#DONE([o2], "o2", fmt:"compact" ) ;#linebreak()
#DONE([o3], "o3", fmt:"none"    ) ;#linebreak()
#SKIP([p0], "p0"                ) ;#linebreak()
#SKIP([p1], "p1", fmt:"full"    ) ;#linebreak()
#SKIP([p2], "p2", fmt:"compact" ) ;#linebreak()
#SKIP([p3], "p3", fmt:"none"    ) ;#linebreak()
